global:
  scrape_interval:     1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'pulsar'
    scrape_interval: 1s
    metrics_path: '/metrics/'
    static_configs:
      - targets: ['host.docker.internal:8080']